### ISSUE TITLE
Determine which collective should be the service provider

### ISSUE THREAD

**Issue by gusaus** [elmsln/openulmus.org#12]
As mentioned in https://github.com/elmsln/openulmus.org/issues/2#issuecomment-328946587 

I think we're just beginning to see the potential opportunity for providing services to other communities in OpenCollective -
https://webpack.academy/
https://reactiveui.academy/

Providing services could be a key element helping sustain Open Ulmus and related projects. Similar to how OpenProducer will be a collective focusing on media https://github.com/OpenProducer/administration/issues/3 should we have a stand-alone collective that focuses on open eductition, training and related services?

**Comment by btopro** [comment]
like split something off of the elmsln one specifically for this endevour? Seems like avoiding a theoretical future issue (elmsln gets collective funds in a generalized as well as through this manner and filtering out said moneys) but whatever makes sense is fine with me.

**Comment by gusaus** [comment]
We want to allocate a % of funds to support the project and operational costs from the getgo.That would be a matter of figuring out how best to manage passing funds from collective to collective. What we're trying to figure out with regards to OpenProducer is similar to what I'm talking about here  https://github.com/OpenProducer/administration/issues/3#issuecomment-321367961

I'm thinking more of a separation of project and service in a marketing/branding sense.  The breadth of services could include more than curriculum and training (again, could be very similar to OpenProducer https://docs.google.com/document/d/1g_IjlDPLclpMSCw76Ntnl6ZhtHxUJ4mmCSHyKveaWcE/edit?usp=sharing) and could target a wide range of OSS projects and communites.
 
So I'm not sure if a service on top of of the project/product collectives (ELMS, Drupal Open Learning, OpenProducer, or even Open Ulmus) would be the best fit. We absolutely would allocate funds to support the projects and operational cost. A stand-alone service collective should also provide separation and flexibility (i.e. members of the aforementioned projects to provide services through the collective; projects could also partner with the collective). 

Ummm.... does that clarify or further confuse?

**Comment by btopro** [comment]
well there are currently 0 supports and no planned usage for ELMSLN related funds. If it's just for supporting this effort from the getgo then cool. We can worry about money going to different things later if that would become an issue but I currently don't forsee that.

**Comment by gusaus** [comment]
I believe subsequent scattered Slack discussions w/ @btopro @mmilutinovic1313 @ikit-claw and others have clarified the need/benefits of stand-alone service collective. 

The next thing to determine is what to call the service. 

The first suggestion I'd like to throw into the ring is [Open Learning Labs](http://openlearninglabs.org/). Main reason being this was actually the original umbrella collective (yes I was calling it a collective from the beginning) behind Drupal Dojo, Drupal Open Learning, Open Producer (here's the outdated project section http://openlearninglabs.org/projects)... and the idea was for the collective to create and house curriculum and training materials for any type of OSS project or program. 

While the current iteration of the website is outdated and inactive, we could easily redo the site, create a collective, and add everybody that wants to provide services as a contributor. 

Thoughts?

**Comment by mmilutinovic013** [comment]
This would work - however is their a benefit in just having an openulmus collective be the umbrella collective? If open ulmus (powered by elmsln) is running these courses would it be the highest order? Or do you envision something above it to house it? I'm still a bit fuzzy on how this will work as none of the collections mentioned in any posts have any financial resources to sustain the building of sites, courses, etc...Is there something I'm missing regarding what the umbrella collective should look like?

**Comment by mmilutinovic013** [comment]
Additionally, you could have the following:

# Open Ulmus Collective
- Provides x% funding to ELMS:LN Collective
- Provides y% funding to IDs, Contributors, etc.
- Provides z% funding to courses of collectives/projects running courses on its platform
# ELMS:LN Collective
- Provides x% funding to AWS hosting
- Provides y% funding for technical projects involving ELMS:LN technologies

This would allow the trickle down effect to work. Since ELMS:LN Collective would only need to eat the cost of AWS, this could allow Open Ulmus to run itself and generate money back to groups that want to host sites on its platform.

**Comment by gusaus** [comment]
We have a great deal of flexibility how we can use OpenCollective to fund the projects we're using and developing. Per https://github.com/elmsln/openulmus.org/issues/12#issuecomment-333180479  I'm thinking more of a separation of project and service in a marketing/branding sense. Per https://github.com/elmsln/openulmus.org/issues/12#issuecomment-333240542 we already have an existing org we could use.

Thumbs up if you agree that Open Learning Labs could be the service that helps sustain all these underlying projects?

**Comment by btopro** [comment]
that sounds reasonable

**Comment by mmilutinovic013** [comment]
Closing this as we have established Open Learning Labs will be the service provider. Creating an issue for implementing open learning labs.
