### ISSUE TITLE
Open Ulmus Course Objectives

### ISSUE THREAD

**Issue by mmilutinovic013** [elmsln/openulmus.org#13]
- [ ] Course Objectives (What do people hope to get out of this course? Skills? Certificate? Etc?)

**Comment by gusaus** [comment]
@mmilutinovic1313 Is this a separate course from https://github.com/elmsln/openulmus.org/issues/7? We definitely want to have an "Intro to Drupal Open Learning" class with similar elements as the Open Ulmus course (how the program works, how to set up a new course, and how to become involved with the community, etc.) but specific to the Drupal Open Learning Program. 

As we'd include the cost in the overall Drupal Open Learning MVP https://github.com/DrupalOpenLearning/drupalopenlearning/issues/1, possibly we should move related issues (or I guess you can't do that on github?) to https://github.com/DrupalOpenLearning/drupalopenlearning or another repo within that org?

**Comment by mmilutinovic013** [comment]
Hi @gusaustin - each of these issues I made last night relates to conversations on objectives. This issue defines what objectives we want to cover in the course described in #7.

**Comment by gusaus** [comment]
@mmilutinovic1313 Wouldn't this and the related issues be 'Open Ulmus' and not 'Drupal Open Learning'? 

Possibly we need to follow up on https://github.com/elmsln/openulmus.org/issues/1#issuecomment-331521363 just make sure we're clear how those relate.

**Comment by mmilutinovic013** [comment]
Speaking of objectives -- is there any talk on gamification? I personally don't like it, but I know many people like badges and proof that they completed xyz objective and are certified in 'whatever' :)

**Comment by mmilutinovic013** [comment]
@gusaus I have changed the scope of this issue and it aligns to the current vision and objectives.

**Comment by cleverington** [comment]
@mmilutinovic1313 With the updated Scope and focus on OpenUlmus Beta, this appears to be an extension of #6, correct?

Would it be simpler to close this issue and integrate the requirements into the overall issue for #6 as checklist?

**Comment by mmilutinovic013** [comment]
Yeah this was intended to be a subtask of #6. But I think @kat-wehr  has a good handle on #6 so I will close this one out
