### ISSUE TITLE
Branding, and Social Media Presence

### ISSUE THREAD

**Issue by mmilutinovic013** [elmsln/openulmus.org#18]
Short and sweet: Does Open Ulmus need a twitter? 
- [x] Twitter Established

**Comment by mmilutinovic013** [comment]
We need to identify someone to do fundraising, social media, and branding for open ulmus. This will allow us to generate $$$ as per our discussions in #15 and #5

**Comment by mmilutinovic013** [comment]
A role has been added to the wiki with this description.

**Comment by mmilutinovic013** [comment]
Once @cleverington joins the project I will add him to this task.

**Comment by cleverington** [comment]
I would leave fundraising as a separate task from Social Media.

One is establishing a brand and presence, the other is actively networking to get contributions by approaching industry leaders across different industries (React, Drupal, WordPress, Polymer, and/or any others identified as a potential opportunity for the group, etc.)

**Comment by mmilutinovic013** [comment]
Updated the issue to reflect this scope

**Comment by cleverington** [comment]
@mmilutinovic1313 
## Short-List of Questions / Thoughts:
 - LastPass for password management for shared passwords?
 - Preferred Username: openulmus
 - What does `Ulmus` actually stand for? (Nothing is fine, just trying to put perspective within the Branding planning.)
 - Social Media Goals (eg What are we attempting to accomplish, for now, or are we merely establishing our presence?)

## Logo & Branding Thoughts
 - Are their funds and/or a Contributor for professional Logo creation?
 - As Open Ulmus has long-term plans to provide support as a sort of "LMS for Open Source Projects" kind-of approach, the Logo will probably need to be system/platform independent

**Comment by mmilutinovic013** [comment]
## Answers:
1. Never heard of it but it sounds reasonable. I use 1Password so idk if it has common integrations.
2. Username sounds good 😄 
3. I believe Ulmus is the Latin for the elm tree. It ties into the ELMS:LN platform. @btopro can verify if I'm crazy or not
4. Establish a presence for now. Twitter is a big one. The ELMS:LN community can help push this out via RTs etc. and we can gain visibility quickly. This could lead to backers soon. 
## Logo 
1. @michael-collins has come up with a ton of cool logos and designs for ELMS:LN so if he was interested I'd recommend him.
2. @btopro may be a better person to ask for that one (sorry I keep tagging ya here)

**Comment by btopro** [comment]
"Elms are deciduous and semi-deciduous trees comprising the flowering plant genus Ulmus in the plant family Ulmaceae." - https://en.wikipedia.org/wiki/Elm. Ulmus is the plant family kingdom that elms are apart of. It is, by classification, bigger then elms :)

**Comment by gusaus** [comment]
Let's work any design and site related topics into our project scope https://github.com/elmsln/openulmus.org/issues/1

Social media, fundraising, outreach could be considered a responsibility of the program managers  (most likely me) initially as we're defining here https://docs.google.com/document/d/11g4tAxHIAu_LuTcDPx-9bFcBqBIxKt85KuKJeT1LvDM/edit?disco=AAAABZff8bw

**Comment by mmilutinovic013** [comment]
Let me know once Twitter is established we can consider this specific issue done once we have social media presence 😁

**Comment by mmilutinovic013** [comment]
#26 is a separate task but will help with branding

**Comment by cleverington** [comment]
@mmilutinovic1313 As Twitter requires an email account, do we have admin@openulmus.org and/or donotreply@openulmus.org available for registration of different Social Media Accounts?

**Comment by mmilutinovic013** [comment]
I'm not sure if email is open that domain - @btopro do you know if we have that setup?

**Comment by mmilutinovic013** [comment]
Currently the collective is setup under my email - but I'll transfer it over once we have a .openulmus.org email

**Comment by btopro** [comment]
no mail currently

**Comment by cleverington** [comment]
https://twitter.com/UlmusOpen has been established using a personal (though ill-used) email address.

Once email has been established, we can simply update. PM me in Slack for pwd.

## Update:
Didn't even notice that Twitter renamed it on creation! lolz.  Deleted unnecessary account.

**Comment by mmilutinovic013** [comment]
https://twitter.com/openulmus existed already. 🤕

**Comment by mmilutinovic013** [comment]
Closing this out as this was merely to establish accounts -- thanks @cleverington! :)

**Comment by btopro** [comment]
Ya, it's mine... lol :)

On Nov 7, 2017 9:38 PM, Mark Milutinovic <notifications@github.com> wrote:

https://twitter.com/openulmus existed already. 🤕

**Comment by cleverington** [comment]
@btopro Do you have LastPass or a different password sharing service available?

@mmilutinovic1313 Do you have a preference?

We can just as easily share a Google Doc with passwords on it, but.... *shrug*  ^_^

Once Mark finishes the branding site for openulmus.org, we'll want to start in on using Social Media to get our presence known (and try and interest backers).

**Comment by mmilutinovic013** [comment]
I've never used last pass but I'd be down to use that. I use 1Password for my personal accounts, but I don't think that has a group share option.

**Comment by btopro** [comment]
1P here so whateer is fine by me
