### ISSUE TITLE
Implement Service Provider: Open Learning Labs

### ISSUE THREAD

**Issue by mmilutinovic013** [elmsln/openulmus.org#19]
We need to implement "Open Learning Labs" to be the service provider for Open Ulmus and its subsequent products.

- [ ] Establish Collective (This may already be done and I don't know it)
- [ ] Establish Operating Budget #15 (Includes #5 cost for courses)
- [ ] Document money flow process

Any volunteers for tackling this issue? I'd propose myself (@mmilutinovic1313) and @gusaus discuss how we can quickly establish preliminary costs so we can get this off the ground for the Drupal Open Learning instance.

**Comment by gusaus** [comment]
Open Learning Labs is in the process of being set up and logging issues here https://github.com/openlearninglabs/administration/issues

Closing this out...
