### ISSUE TITLE
Open Ulmus Consulting?

### ISSUE THREAD

**Issue by mmilutinovic013** [elmsln/openulmus.org#20]
Would it be ideal to have a consultant role on the Open Ulmus team to set up the PaaS for interested groups? Would this be a single dedicated person? Or would core contributors and apprentices have the opportunity to set this up for extra $$ and time?

https://github.com/elmsln/openulmus.org/wiki/(4)-Requesting-an-Open-Ulmus-Consultant

**Comment by gusaus** [comment]
@mmilutinovic1313 Are we're talking about the combo of roles/skills that @btopro previously described? https://github.com/DrupalOpenLearning/drupalopenlearning/issues/2#issuecomment-336237002

If so, would that be you & @djfusco?

**Comment by mmilutinovic013** [comment]
That seems reasonable. I will add to the wiki that these two roles can use x% of their time helping set up Open Ulmus for other organizations.

**Comment by mmilutinovic013** [comment]
Closing this as a duplicate based on this :)
