### ISSUE TITLE
Draft Initial Open Ulmus Budget

### ISSUE THREAD

**Issue by mmilutinovic013** [elmsln/openulmus.org#23]
Let's consolidate all the info on Hosting, Labor, and other costs on this document. This can eventually translate into a spreadsheet if needed. 

https://docs.google.com/document/d/1QkWDblIetxMKwDgPklK9Gi9oRaz8_6pReWSyNHpNL8Q/edit

**Comment by cleverington** [comment]
Converted into Wiki page at https://github.com/elmsln/openulmus.org/wiki/6.-Budget-and-Sustainability

Closing issue.
