### ISSUE TITLE
Set up open collective for Open Ulmus 

### ISSUE THREAD

**Issue by gusaus** [elmsln/openulmus.org#25]
Per our discussions we should definitely set up a collective for Open Ulmus. This can be set up rather quickly by going to https://opencollective.com/apply and setting up as 'Other'. 

Once set up we probably should add all team members we're listing here? 
https://github.com/elmsln/openulmus.org/wiki/2.-Open-Ulmus-Core-Team

Also we can edit the copy and figure out the sponsor/contributor levels.

You wanna give it a shot @mmilutinovic1313 ?

**Comment by mmilutinovic013** [comment]
Yessir can do!

**Comment by mmilutinovic013** [comment]
"Open Ulmus is a collective that provides open education powered by the ELMS:LN project."

**Comment by mmilutinovic013** [comment]
How is that for a description?

**Comment by mmilutinovic013** [comment]
https://opencollective.com/openulmus

We can edit the descriptions as needed! :)

**Comment by gusaus** [comment]
@mmilutinovic1313 Couple things we still need to decide and fine tune -

- [x] we should add all team members to the collective (once their involvement is confirmed) -  
https://github.com/elmsln/openulmus.org/wiki/2.-Open-Ulmus-Core-Team (see https://forum.opencollective.com/t/how-to-add-contributors-to-your-collective/74) 
- [ ]  we should finalize our initial fundraising strategy https://github.com/elmsln/openulmus.org/issues/22 before we run with the sponsor/backer levels currently on the collective
- [ ]  we'll need to link the collective to a host org (most likely that will be OpenCollective unless we want to be a host ourselves https://forum.opencollective.com/t/what-to-know-if-i-want-to-be-a-host/33) 

We can discuss more in Slack if that'll help.

**Comment by mmilutinovic013** [comment]
Closing this out as we will add tiers here and on branding site once the fundraising strategy is settled. I'll ping you about the host org link too.
