### ISSUE TITLE
Initial Branding Site for Open Ulmus

### ISSUE THREAD

**Issue by mmilutinovic013** [elmsln/openulmus.org#27]
I propose that we build out an initial branding site for Open Ulmus that we can host info on our Wiki, links to collective page, and other information to sell our brand. #18 This will allow for the open collective page to have more credibility and can help with social media presence etc. This should be built with Grav as Grav is being incorporated (for this purpose) into ELMS:LN core currently.

- [x] Build initial Grav site on localhost and this repository domain
- [x] Migrate Site to Open Ulmus website

Note: This task can be completed without the site migration. As long as we have a main location for this info to be housed we will be okay :)

**Comment by mmilutinovic013** [comment]
If we don't have any other interested parties in this task - I'd be happy to take an initial stab at getting this up and running after my other design and budget tasks are complete.

**Comment by cleverington** [comment]
I assume you are referring to https://learn.getgrav.org/basics/what-is-grav ?

**Comment by mmilutinovic013** [comment]
Yes - that is being added to ELMSLN core. I don’t think it can run as a GH Pages site tho.

**Comment by gusaus** [comment]
Are we talking about https://openulmus.org/? If so, I think we need to reconcile with previous thoughts https://github.com/elmsln/openulmus.org/issues/1#issuecomment-336267013 and work out the details in our site spec.

**Comment by mmilutinovic013** [comment]
Yeah, the https://www.udemy.com/ site looks similar to my vision for how this site should look. Perhaps our interface can even be simpler?

**Comment by mmilutinovic013** [comment]
Posted in here regarding the feature making it into core. If @btopro indicates that we could hook up grav alongside elmsln in the same server then I believe this issue can be resolved quickly (for an MVP branding site) https://github.com/elmsln/elmsln/issues/2300

**Comment by mmilutinovic013** [comment]
I'll assign myself to this once I get an answer on the feasibility of grav within our current domain

**Comment by btopro** [comment]
@mmilutinovic1313 I think we can hook it up; maybe this can be a goal for when your here in the not too distant future?

**Comment by mmilutinovic013** [comment]
Yessir - I'm working on this locally for now and then we can work together to get this into core!

**Comment by cleverington** [comment]
@mmilutinovic1313 Deployed the site today!

Will be opening a separate issue for a few of the observations we made on site-launch.
