### ISSUE TITLE
Set up the AWS account

### ISSUE THREAD

**Issue by btopro** [elmsln/openulmus.org#3]
Determine which ELMS member should own and control the AWS account (preferably beginning with AWS free tier)
Set up the billing so when there is a usage cost it could be drawn from https://opencollective.com/elmsln, not the individual setting up the AWS account
Determine who should manage and maintain ELMS on AWS

**Comment by gusaus** [comment]
> Determine which ELMS member should own and control the AWS account (preferably beginning with AWS free tier)

Probably best for the ELMS member doing this currently to keep owning and controlling. Would there be any reason why we 'couldn't start with https://aws.amazon.com/free/?

> Set up the billing so when there is a usage cost it could be drawn from https://opencollective.com/elmsln, not the individual setting up the AWS account

Assuming there will be enough funds in https://opencollective.com/elmsln, there are already ways to do this. 

> Determine who should manage and maintain ELMS on AWS

Would the same person set it up? Either way, we should determine the time/cost needed for someone to take the lead. #1

**Comment by btopro** [comment]
platform needs 2 gigs to install due to mariadb / mysql requirement to get up and running. Other then that I don't think so

**Comment by djfusco** [comment]
A couple of comments: 1.  You'll want to think about your storage and the type you'll want to grow into - it's most likely the one thing that might give you some hassle.  It's supposed to be seamless, but moving from one storage type to another can sometimes be tricky.  CPU and RAM tend to be easier.  Free isn't free forever.  Unless you like moving stuff around under different accounts to keep it free - https://aws.amazon.com/free/  Usually you'll get a year or so out of the free service.  Otherwise, it's great.  BTW - you'll also want to set up logging ahead of time and look at the cost for that; default logging is your own console.log etc. unless you turn on the good stuff.  But, watch your usage closely as this can run up charges as well.

**Comment by gusaus** [comment]
Walking someone through this excellent tutorial would be a great learning exercise - 
http://drdavefusco.com/installing-elmsln-on-aws-and-configuring-xapi-and-h5p/

Are there any mentors and apprentices interested in participating?

**Comment by djfusco** [comment]
Sure, @gusaus, if you're looking for someone to help w/ this, let me know.  I'd be glad to help.

**Comment by btopro** [comment]
@djfusco what about the idea of getting a student to do it as a project / something to learn? Know any students that would be interested in doing this w/ mentoring for help? My whole thing with this is that I will NOT do it personally because I want to show someone else what / how to do something and have them ask questions. Someone not affiliated with our group would be best

**Comment by CybersecDan** [comment]
@btopro I'd be happy to learn some stuff and ask lots of questions. What can I do to help?

**Comment by btopro** [comment]
@danielrose28 thanks for asking. Give this a thumb through https://docs.google.com/document/d/11g4tAxHIAu_LuTcDPx-9bFcBqBIxKt85KuKJeT1LvDM/edit and see if this is of interest in participating in :) We need someone to throw up an AWS server.

**Comment by CybersecDan** [comment]
@btopro Just looked through it. I'm definitely interested. Full disclosure, I've never done anything with AWS. I do have some server admin experience. My personal blog is hosted on DigitalOcean, which required me to setup the server and install D8, etc. It was a lot of fun and very sysadmin-like. As you know, I'm always eager to learn though.

**Comment by btopro** [comment]
Can probably use this to get a sense of how to do it -- http://drdavefusco.com/installing-elmsln-on-aws-and-configuring-xapi-and-h5p/

As far as your history, I'll give you my world view and you can discern if that invalidates you or not: https://en.wikipedia.org/wiki/The_New_Colossus#Contents
;)

**Comment by djfusco** [comment]
@btopro @danielrose28 yeah, I can get you a student or two.  Just so I'm clear, you want them (the student(s)) to be the one who actually builds the AWS instance?  And others follow along and answer questions when they come up?  Sounds odd, but the biggest challenge with this is - which credit card is going to be used to set up the AWS instance?  I don't want to ask a student to do that.  Let me know when you want to get started on this and I'll get the word out.

**Comment by CybersecDan** [comment]
@btopro @djfusco I don't mind giving it a shot, but it's up to you guys. Whatever you think is best. Either way, I'm happy to help in some way.

**Comment by btopro** [comment]
Im cool w/ danielrose doing it but as has come up before @gusaus , the question of who's paying for this thing remains, lol.

**Comment by gusaus** [comment]
I think the idea was to have the ELMS lead @btopro own the AWS account and have his card on file.  We should include the cost to setup and maintain in #1 and make sure there are funds in https://opencollective.com/elmsln to cover the cost once the AWS free tier is up.

Does that sound about right?

**Comment by djfusco** [comment]
As you can imagine, the credit card is kept on file and only used either a. after the first year or b. someone creates a solution that chews up lots of CPU/RAM/Storage, etc.  As an FYI, I did this with my class (had them set up an AWS account for a project) and they each put their credit card info in, with the understanding it was for class only.  Not a long(er) term solution, but if you just want to do this for a demo/learning sake, it's not normally a problem.

**Comment by gusaus** [comment]
With regards to https://github.com/elmsln/openulmus.org/issues/3#issuecomment-316752633, I think the ideal is to find mentors and apprentices for every role we're trying to identify in #2 

I believe we've decided that anyone interested in collaborating or learning about this or related projects should join #elmsln in https://slack.opencollective.com/.  Possibly read over https://opencollective.com/faq if you're wondering what OpenCollective is all about.

Once we have this set up, the next step is to help create curriculum and training for projects and groups already in the community. https://opencollective.com/opensource#collectives

**Comment by btopro** [comment]
I have a box, i have a install, I have to migrate the stuff I currently use that's on there, repoint cloudflare and it should be good to proceed in that regard. I didn't want to have to just do this but if my card is already on it and I was making accounts it seemed weird to not copy and paste what I would have told someone else to. Still will gladly accept help on the project, just not on the credit card entry part :)

http://54.174.180.231/

**Comment by CybersecDan** [comment]
@btopro No problem. I understand. I'm always happy to help in other ways as well.

**Comment by gusaus** [comment]
@btopro Might still be good source material for a Drupal Dojo session or something similar as a way to showcase ELMS and get others involved. 

Also, do we still need someone tasked with maintaining the AWS setup ongoing? 

We should list out all our ongoing needs in #2.

**Comment by btopro** [comment]
or a full stack dev. someone that's going to need to understand the server for upgrades and what not.

**Comment by mmilutinovic013** [comment]
@danielrose28 -- are there any other roles on that document you would be interested in learning about or ways you would like to help out? The more the merrier. Always trying to grow a bigger and stronger community!

**Comment by CybersecDan** [comment]
I'm interested in anything technical. Sysadmin apprentice, tech lead apprentice, webmaster apprentice.

**Comment by mmilutinovic013** [comment]
I'll add you under SysAdmin apprentice since you said you wanted to learn more about that type of role! I'll keep you posted. Feel free to ping me on here, slack, or twitter if you have any questions!

**Comment by CybersecDan** [comment]
Sounds great! Thank you. Looking forward to helping. :)

**Comment by btopro** [comment]
There is a server, mark bug me via email to figure out how to add you to the aws console for it

**Comment by gusaus** [comment]
@mmilutinovic1313 @danielrose28 As we're trying to combine forces with the [Drupal Open Learning program](https://github.com/DrupalOpenLearning) (Open Ulmus will house the curriculum and learning resources), there are overlapping needs and mentoring opportunities. 

With regards to sysadmin activities, we're looking for some help with our Pantheon environment https://github.com/DrupalOpenLearning/drupaldojo/issues/2

We're trying to get everybody involved or interested to join #drupalopenlearning room in http://drupalslack.herokuapp.com/

Join us if you can!

**Comment by CybersecDan** [comment]
I'll join the channel for sure. Sorry for limited response this week. I'm on vacation til the end of the week.

**Comment by gusaus** [comment]
@danielrose28 Glance over https://github.com/DrupalOpenLearning/drupaldojo/issues/2 and comment if you're insterested in helping manage. 

Considering the [founder of Drupal Dojo](https://groups.drupal.org/node/516465) is also cofounder of Pantheon, we'll most likely get whatever resources we need to do the job!

**Comment by djfusco** [comment]
Let me know when you'd like some help from my end and/or students

**Comment by gusaus** [comment]
@djfusco Is there a specific area you and your students could help with? Learning AWS, sysadmin, and related skills?

**Comment by djfusco** [comment]
Yep - learning AWS, setting up the environment, DNS, sysadmin stuff. As well as the xAPI side if there is interest in adding additional statement endpoints, tincan libraries, and data extraction.  tying other systems in, integration, and data visualization if you're interested.

**Comment by gusaus** [comment]
Nice! We have at least two other OSS platforms we'll be setting up and managing on AWS. Like Open Ulmus, we want to create learning materials and provide students with hands on experience. 

Most likely many other projects would like a similar thing once we ramp up our [Drupal Open Learning program](https://github.com/drupalopenlearning) and/or offer services to [projects in OpenCollective](https://opencollective.com/opensource#collectives).

Out of scope for this issue, but I think we need to figure out who would be providing such a service.

**Comment by gusaus** [comment]
@mmilutinovic1313 Do we still need help with this particular task?

**Comment by gusaus** [comment]
Are we fully ported over to AWS? Do we still need people/resources to manage and maintain?

**Comment by btopro** [comment]
yes this is ported over and currently delivered from it
