### ISSUE TITLE
Fix Sign-in Issues

### ISSUE THREAD

**Issue by mmilutinovic013** [elmsln/openulmus.org#42]
This could be related to services protecting the site. @btopro and I will look into how to make sure these services don't interfere with sign-in and permissions for openulmus.org and its subsequent domains.

**Comment by btopro** [comment]
I made some /etc/hosts things, give it a shot and see if it helps

**Comment by mmilutinovic013** [comment]
Testing ATM

**Comment by mmilutinovic013** [comment]
Still Running into Access Denied Errors. Ran `leafy 6` to clean up permissions and no changes.

**Comment by cleverington** [comment]
## Update and Complete

Issue appears resolved. Tested logging and logging out via multiple browsers over a week period and no issues.  Closing as unable to currently duplicate.
