### ISSUE TITLE
Error: courses.openulmus.org - Errors should only display for Admins or not at all

### ISSUE THREAD

**Issue by cleverington** [elmsln/openulmus.org#47]
See https://people.openulmus.org/admin/config/development/logging

**Comment by cleverington** [comment]
## Updated

**Comment by mmilutinovic013** [comment]
Is this the chosen error?

**Comment by cleverington** [comment]
I just turned off errors completely. They'll still track in Watchdog, but will not load to _Users_ on every pageload.

Had the URL wrong though, see https://online.openulmus.org/admin/config/development/logging for errors.

**Comment by mmilutinovic013** [comment]
Reopening based of @cleverington 's comment on Slack:

> If drush is installed, you can login to the server and run this to get rid of it using this command: `drush sql-query "DELETE from system where type = 'module' AND name = 'chosen';" `  You'd need to do it from the docroot online.openulmus.org is being loaded from.


I will run this command tomorrow when it is not late at night on the east coast and I risk bricking the server.

**Comment by mmilutinovic013** [comment]
Closing as duplicate
