### ISSUE TITLE
Wiki Page - 2.-Open-Ulmus-Core-Team

### ISSUE THREAD

**Issue by cleverington** [elmsln/openulmus.org#56]
## Issue

Need to adjust *Program Managers* to include Mark's stepping back from full compliment of PM tasks.

URL: https://github.com/openulmus/openulmus.org/wiki/2.-Open-Ulmus-Core-Team

**Comment by btopro** [comment]
updated to reflect Mark having knowledge of the PM side but not being primary on it at this time
