### ISSUE TITLE
Evaluate operating Open Ulmus as a project of Open Collective Foundation 501(c3)

### ISSUE THREAD

**Issue by gusaus** [elmsln/openulmus.org#57]
The following is pulled out of [this thread in OpenCollective slack](https://opencollective.slack.com/archives/C6464RTMK/p1518037696000404) 

[Open Collective Foundation](https://opencollective.com/foundation#about) is a 501c3 whose mission is to promote projects in the US with the following charitable purposes: 
* increasing access to educational resources and training
* creating a positive social impact and. 
* developing tools to improve civic participation within cities or communities.

Based on that description and the scope of some of the [other collectives they’re already hosting](https://opencollective.com/foundation#hosting), it seems like the the Open Ulmus mission would be in scope -
> Open Ulmus is an OpenCollective sustained project allowing for public production and sharing of knowledge. Open Ulmus is powered by ELMS:LN and utilizes open source projects to help improve the quality and availability of education and training on a global scale.

As Open Collective Foundation is just getting started, the benefits of such a relationship are being worked out [in this document](https://opencollective.slack.com/files/U2LPSFDKK/F7W1W6BKR/501c_3_). A few of which are as follows:

* Extra incentive for sponsors: donations are tax-deductible
* [Umbrella collective](https://opencollective.com/foundation-collective#about) could be a conduit for funds and other resources

As mentioned in the thread, we'd most likely need to make some adjustments to our mission and service model to ensure we'd be approved (we can address specific changes in related issues).

While @btopro @kat-wehr and myself already onboard with going this route, it's important the entire team is looped in and able to follow up with questions, concerns, requests for clarification or just :+1: here or in the thread.

**Comment by cleverington** [comment]
I am on board with moving forward on 501(c3).

A solid child-task of this issue would be itemizing the requirements to *qualify* as 501(c3) and what steps/tasks need to be taken in order to apply/create/I-dont-know-other-tasks?

**Comment by gusaus** [comment]
With 4 of 6 active team members 👍 to proceed (we should point out that Mark was interested in this direction), I'd like to close this out after @michael-collins and @djfusco have a chance to review and weigh in with comments or a 👍 

> A solid child-task of this issue would be itemizing the requirements to qualify as 501(c3)

#58 has already been set up with the intent to tackle those issues.

One final note - While there was a lot of ground covered in the 12/04/2017 meeting https://github.com/openulmus/openulmus.org/issues/45, my personal view (as one of 3 team members on the call) was/is that 1) a good bit of discussion was more in scope to Open Learning Labs (a service provider/partner of Open Ulmus https://github.com/openlearninglabs/administration/issues/6) and anything specific to 'this' collective/organization needed input from the entire Open Ulmus team to lock down any issue. 

Now that we've made through the holidays we should move forward as a team with awareness of how our resources and opportunities have evolved.

**Comment by djfusco** [comment]
@gusaus I think the non-profit path is a good way to go.  If investors in the future really aren't a need, then this decision is fine.  I'd recommend Legalzoom for online registration, unless you've already done it.  Easy and inexpensive.

**Comment by gusaus** [comment]
The relationship we’d be forming is essentially [fiscal sponsorship](https://en.wikipedia.org/wiki/Fiscal_sponsorship) with [Open Collective Foundation 501(c3)](https://opencollective.com/foundation). As the foundation is very new, the Open Collective team and community is [just beginning to define process, requirements, benefits](https://slack-files.com/T0HSL38JD-F7W1W6BKR-b544b17037), and other things that will help them onboard collectives.  

We'll leave this open for @michael-collins, but the next steps are outlined in #58

**Comment by michael-collins** [comment]
I'm stretched pretty thin right now, hence why my responses are so lagged. I'm in, sounds like a good direction. Admittedly, I know little about forming this type of org.

**Comment by gusaus** [comment]
> I'm stretched pretty thin right now, hence why my responses are so lagged.

That is a big reason why we should go this route. 

Think we can close this out and move on to making it happen #58
