### ISSUE TITLE
Getting Started with Drupal Course (drupal dojo)

### ISSUE THREAD

**Issue by mmilutinovic013** [elmsln/openulmus.org#8]
I'm thinking it might be a cool idea to have an open ulmus course for "getting started with drupal" We can run this by the drupal dojo folks for what information would be best to have and if they'd like to incorporate information about the dojo in this course.

**Comment by mmilutinovic013** [comment]
This is dependent on #11 as they would need D8 for a course to be created for them.

**Comment by gusaus** [comment]
Unless there's a budget, I wouldn't recommend first focusing on a "getting started with drupal" course. One of our primary goals with Drupal Open Learning (an instance of Open Ulmus) will be to enable others to produce and sustain themselves. 

That said, most of the projects we're evaluating as [Drupal Open Learning projects](https://github.com/DrupalOpenLearning/drupalopenlearning/projects/2) will require courses, tutorials, docs, training vids and other elements members of this group could provide with a budget. 

Does that make sense?

**Comment by mmilutinovic013** [comment]
That makes sense to me. I'll close this issue out and if it happens that there is a budget for this in the future. We can revisit this.
